version: '2'

services:
  graphql-server:
    container_name: dev-graphql-server-4000
    build:
      context: graphql-server-4000
      dockerfile: Dockerfile.dev
      args:
        - PORT=${GRAPHQL_SERVER_PORT}
    image: dev-graphql-server-image
    ports:
      - '${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}'
    volumes:
      - ./graphql-server-4000/src:/usr/src/app/src
    environment:
      - PORT=${GRAPHQL_SERVER_PORT}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
    networks:
      - predictivehire
       
  api-gateway:
    container_name: dev-api-gateway
    build:
      context: api-gateway-3000
      dockerfile: Dockerfile.dev
      args:
        - PORT=${API_GATEWAY_PORT}
    image: dev-api-gateway-image
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    volumes:
      - ./api-gateway-3000/src:/usr/src/app/src
    environment:
      - PORT=${API_GATEWAY_PORT}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - COMPANY_SERVICE_HOST=${COMPANY_SERVICE_HOST}
      - COMPANY_SERVICE_PORT=${COMPANY_SERVICE_PORT}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - VACANCY_SERVICE_PORT=${VACANCY_SERVICE_PORT}
      - VACANCY_SERVICE_HOST=${VACANCY_SERVICE_HOST}
    networks:
      - predictivehire
    depends_on:
      - user-service
      - auth-service
      - company-service

  auth-service:
    container_name: dev-auth-service
    build:
      context: microservices/auth-service-8080
      dockerfile: Dockerfile.dev
      args:
        - PORT=${AUTH_SERVICE_PORT}
    image: dev-auth-service-image
    ports:
      - '${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}'
    volumes:
      - ./microservices/auth-service-8080/src:/usr/src/app/src
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
    networks:
      - predictivehire

  user-service:
    container_name: dev-user-service
    build:
      context: microservices/user-service-8001
      dockerfile: Dockerfile.dev
      args:
        - PORT=${USER_SERVICE_PORT}
    image: dev-user-service-image
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
    volumes:
      - ./microservices/user-service-8001/src:/usr/src/app/src
    environment:
      - PORT=${USER_SERVICE_PORT}
      - DB_URL=mongodb://dev-user-service-mongo-db/users
    networks:
      - predictivehire
      - user-service-private-network
    depends_on:
      - user-service-mongo-db

  vacancy-service:
    container_name: dev-vacancy-service
    build:
      context: microservices/vacancy-service-8002
      dockerfile: Dockerfile.dev
      args:
        - PORT=${VACANCY_SERVICE_PORT}
    image: dev-vacancy-service-image
    ports:
      - '${VACANCY_SERVICE_PORT}:${VACANCY_SERVICE_PORT}'
    volumes:
      - ./microservices/vacancy-service-8002/src:/usr/src/app/src
    environment:
      - PORT=${VACANCY_SERVICE_PORT}
      - DB_URL=mongodb://dev-vacancy-service-mongo-db/vacancy
    networks:
      - predictivehire
      - vacancy-service-private-network
    depends_on:
      - vacancy-service-mongo-db

  company-service:
    container_name: dev-company-service
    build:
      context: microservices/company-service-8003
      dockerfile: Dockerfile.dev
      args:
        - PORT=${COMPANY_SERVICE_PORT}
    image: dev-company-service-image
    ports:
      - '${COMPANY_SERVICE_PORT}:${COMPANY_SERVICE_PORT}'
    volumes:
      - ./microservices/company-service-8003/src:/usr/src/app/src
    environment:
      - PORT=${COMPANY_SERVICE_PORT}
      - DB_URL=mongodb://dev-company-service-mongo-db/company
    networks:
      - predictivehire
      - company-service-private-network
    depends_on:
      - company-service-mongo-db

  user-service-mongo-db:
    image: mongo
    container_name: dev-user-service-mongo-db
    volumes:
      - users_data:/data/configdb
      - users_data:/data/db
    ports:
      - 27017:27017
    networks:
      - user-service-private-network

  vacancy-service-mongo-db:
    image: mongo
    container_name: dev-vacancy-service-mongo-db
    volumes:
      - vacancies_data:/data/configdb
      - vacancies_data:/data/db
    ports:
      - 27018:27017
    networks:
      - vacancy-service-private-network

  company-service-mongo-db:
    image: mongo
    container_name: dev-company-service-mongo-db
    volumes:
      - companys_data:/data/configdb
      - companys_data:/data/db
    ports:
      - 27019:27017
    networks:
      - company-service-private-network

networks:
  predictivehire:
  user-service-private-network:
  vacancy-service-private-network:
  company-service-private-network:

volumes:
  users_data:
  vacancies_data:
  companys_data:
