version: '2'

services:
  api-gateway:
    container_name: dev-api-gateway
    build:
      context: ./src/api-gateway-3000
      dockerfile: Dockerfile.dev
      args:
        - PORT=${API_GATEWAY_PORT}
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    volumes:
      - ./src/api-gateway-3000:/usr/src/app
    environment:
      - PORT=${API_GATEWAY_PORT}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_TCP_PORT=${AUTH_SERVICE_TCP_PORT}
    networks:
      - predictivehire
    depends_on:
      - user-service
      - auth-service

  user-service:
    container_name: dev-user-service
    build:
      context: ./src/microservices/user-service-8001
      dockerfile: Dockerfile.dev
      args:
        - PORT=${USER_SERVICE_PORT}
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
    volumes:
      - ./src/microservices/user-service-8001:/usr/src/app
    environment:
      - PORT=${USER_SERVICE_PORT}
      - DB_URL=mongodb://dev-user-service-mongo-db/users
    networks:
      - predictivehire
      - user-service-private-network
    depends_on:
      - user-service-mongo-db

  auth-service:
    container_name: dev-auth-service
    build:
      context: ./src/microservices/auth-service-8080
      dockerfile: Dockerfile.dev
      args:
        - HTTP_PORT=${AUTH_SERVICE_HTTP_PORT}
        - TCP_PORT=${AUTH_SERVICE_TCP_PORT}
    ports:
      - '${AUTH_SERVICE_HTTP_PORT}:${AUTH_SERVICE_HTTP_PORT}'
      - '${AUTH_SERVICE_TCP_PORT}:${AUTH_SERVICE_TCP_PORT}'
    volumes:
      - ./src/microservices/auth-service-8080:/usr/src/app
    environment:
      - HTTP_PORT=${AUTH_SERVICE_HTTP_PORT}
      - TCP_PORT=${AUTH_SERVICE_TCP_PORT}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
    networks:
      - predictivehire

  user-service-mongo-db:
    image: mongo
    container_name: dev-user-service-mongo-db
    volumes:
      - users_data:/data/configdb
      - users_data:/data/db
    ports:
      - 27017:27017
    networks:
      - user-service-private-network

networks:
  predictivehire:
  user-service-private-network:

volumes:
  users_data:
