version: '2'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway-3000
      args:
        - PORT=${API_GATEWAY_PORT}
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    environment:
      - PORT=${API_GATEWAY_PORT}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
    networks:
      - predictivehire
    depends_on:
      - user-service

  user-service:
    container_name: user-service
    build:
      context: ./microservices/user-service-8001
      args:
        - PORT=${USER_SERVICE_PORT}
    ports:
      - '${USER_SERVICE_PORT}:${USER_SERVICE_PORT}'
    environment:
      - PORT=${USER_SERVICE_PORT}
    networks:
      - predictivehire

  auth-service:
    container_name: auth-service
    build:
      context: ./microservices/auth-service-8080
      args:
        - PORT=${AUTH_SERVICE_PORT}
    ports:
      - '${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}'
    environment:
      - PORT=${AUTH_SERVICE_PORT}
    networks:
      - predictivehire

networks:
  predictivehire:
